### ISSUE TITLE
Prediction of Covid-19

### ISSUE THREAD

**Issue by theanshulcode** [ayeshafalak/covidcases_prediction#1]
In this, I will use the dataset you have provided and predict the cases according to my knowledge. The notebook will contain data engineering, data visualization.

**Comment by suy1968** [comment]
In this,  we Create a Machine Learning Project using Supervised Learning technique to predict the number of cases of covid in upcoming days with different algorithms

**Comment by ayeshafalak** [comment]
> In this, I will use the dataset you have provided and predict the cases according to my knowledge. The notebook will contain data engineering, data visualization.

You can find the dataset at : https://www.kaggle.com/punyaslokaprusty/covid-19-india-tracking

**Comment by ayeshafalak** [comment]
> In this, we Create a Machine Learning Project using Supervised Learning technique to predict the number of cases of covid in upcoming days with different algorithms

Yes.

**Comment by theanshulcode** [comment]
> > In this, I will use the dataset you have provided and predict the cases according to my knowledge. The notebook will contain data engineering, data visualization.
> 
> You can find the dataset at : https://www.kaggle.com/punyaslokaprusty/covid-19-india-tracking

Thank you @ayeshafalak .
