### ISSUE TITLE
Add Contribution Guidelines, License and Code of Conduct in Readme File.

### ISSUE THREAD

**Issue by Shaishav0507** [ayeshafalak/covidcases_prediction#19]
Hi @ayeshafalak
I would like to add contributing.md file in the repo and link it and other files in the readme file.
Please assign it to me.
Thanks

**Comment by Ayan-thecodeking** [comment]
I also want to work on this issue please assign this to me , i'll do it for sure 
:) thanks @ayeshafalak

**Comment by Shaishav0507** [comment]
@ayeshafalak 
Why is it duplicate ?
It's not added in your readme file

**Comment by Shaishav0507** [comment]
Or you don't want to add it in your readme file. @ayeshafalak
