### ISSUE TITLE
add more badges to README.md file

### ISSUE THREAD

**Issue by Umesh-01** [ayeshafalak/covidcases_prediction#24]
**Describe the solution you'd like**
I will add some more badges to the top of readme.md file so that it will look more interactive and awesome, since the badges will be colorful and more attractive than the text the users will like it and it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

**And the present image is of no use see this--**

![image](https://user-images.githubusercontent.com/83420185/122448099-089c5400-cfc2-11eb-81bc-e62598188527.png)

**and after clicking on it the user is redirected to this**

![image](https://user-images.githubusercontent.com/83420185/122448212-25388c00-cfc2-11eb-8f65-23a3ef2b8ea4.png)

**which is of no use...**

**Comment by Umesh-01** [comment]
@ayeshafalak Should I make these changes??

**Comment by Wittty-Panda** [comment]
can i work on this @ayeshafalak
