### ISSUE TITLE
Prediction using Linear Regression

### ISSUE THREAD

**Issue by ayeshafalak** [ayeshafalak/covidcases_prediction#8]

**Comment by skimran2000** [comment]
Could you pleaase assign this issue to me

**Comment by harshita9621** [comment]
could you please assign this issue to me

**Comment by Sakshi1007** [comment]
Could you plz assign this to me?

**Comment by SagarDhandare** [comment]
This work done by @skimran2000 
@ayeshafalak : Please take this to your end 🙂
